# -*- coding: utf-8 -*-
"""LDR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1us-S924ohqqbbpan5LHU0Ccksb0ShXEa
"""

!pip install paho-mqtt

import random
import time
from datetime import datetime
import sqlite3

# Create database
conn = sqlite3.connect("sensor_data.db")
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS light_data (
    time TEXT,
    value INTEGER
)
""")

# Simulate sensor readings
for i in range(60):  # 60 samples
    light_value = random.randint(300, 3500)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    cursor.execute(
        "INSERT INTO light_data VALUES (?, ?)",
        (timestamp, light_value)
    )

    print(timestamp, light_value)
    time.sleep(1)

conn.commit()
conn.close()

import sqlite3
import pandas as pd

conn = sqlite3.connect("sensor_data.db")
df = pd.read_sql_query("SELECT * FROM light_data", conn)
conn.close()

df.head()

import matplotlib.pyplot as plt

plt.figure()
plt.plot(df["time"], df["value"])
plt.xticks(rotation=45)
plt.xlabel("Time")
plt.ylabel("Light Intensity")
plt.title("Simulated IoT Light Sensor Data")
plt.tight_layout()
plt.show()

df.to_csv("light_sensor_data.csv", index=False)